obj-y      += huawei_charger.o
obj-y      += huawei_fuelguage.o
obj-$(CONFIG_HUAWEI_BATT)      += huawei_battery.o
obj-$(CONFIG_HUAWEI_BATT2)      += huawei_battery2.o
obj-$(CONFIG_HUAWEI_PMU_DSM) += huawei_dsm_charger.o
