# lcdkit-dtsi-parser.pl


my $LCD_KIT_TOOLPATH = "../../../../../chipset_common/devkit/lcdkit/lcdkit3.0/tools";
my $paranum = 0;
my $platform = $ARGV[$paranum];
$paranum++;
my $target_file_type = $ARGV[$paranum];
$paranum++;

if ($platform eq 'qcom')
{
    require "./lcdkit-base-lib.pl";
}
else
{
    require "$LCD_KIT_TOOLPATH/lcd_kit_base_lib.pl";
}

# initialize the parser
my $lcd_xml_parser = new XML::LibXML;
my $parse_error_string = get_err_string();

debug_print("get chip platform is : $platform\n");
my $out_dtsi_file = $ARGV[$paranum];
$paranum++;
debug_print("get dtsi file path is : $out_dtsi_file\n");

my $xml_file_num = uc($ARGV[$paranum]);
$paranum++;
debug_print("get xml file number is $xml_file_num\n");

if(scalar @ARGV < ($xml_file_num + $paranum))
{
    error_print(($xml_file_num + $paranum) . " command line arguments required.\n");
    error_print("1-chip platform(hisi or qcom)\n");
    error_print("2-out file path of dtsi file\n");
    error_print("3-the number of XML Document to be parsed\n");
    error_print("4-". ($xml_file_num + $paranum) . ":XML Documents to parse\n");

    exit 1;
}

my @lcd_xml_doc;
my @lcd_xml_files;
for (my $count = 0; $count < $xml_file_num; $count++) {
    debug_print("get para file [$count] is $ARGV[$count + $paranum]\n");
    push(@lcd_xml_files, $ARGV[$count + $paranum]);
    push(@lcd_xml_doc, $lcd_xml_parser->parse_file($ARGV[$count + $paranum]));
}

my $panel_file_name = file_name_from_path($out_dtsi_file);
welcome_print_begin(\@lcd_xml_files, $panel_file_name);

my $xml_version = parse_multi_xml('/hwlcd/Version');
if ($xml_version eq $parse_error_string) {
    error_print("get error xml file version!\n");
    exit_with_info($panel_file_name, 1);
}
debug_print("xml file version is : $xml_version\n");

print "=====================parsing dtsi file: $panel_file_name.dtsi ======================\n";

#generater dtsi file used in kernel
open (my $panel_dtsi_file, '>'.$out_dtsi_file) or die "fail to open file $out_dtsi_file\n";

print $panel_dtsi_file create_dtsi_header($panel_file_name, $xml_version, $target_file_type);

#add entry if need, and please keep alignment, thanks!
my @dtsi_property_strings = (
        # the parameter of lcd device 
        ['/hwlcd/PanelEntry/PanelCompatible',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\tcompatible = ",                                ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelName',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\tlcd-kit,panel-name = ",                        ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelType',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\tlcd-kit,panel-type = <",                       ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelXres',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\tlcd-kit,panel-xres = <",                       ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelYres',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\tlcd-kit,panel-yres = <",                       ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelWidth',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\tlcd-kit,panel-width = <",                      ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelHeight',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\tlcd-kit,panel-height = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelOnCommand',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,panel-on-cmds = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelOnCommandState',           \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\tlcd-kit,panel-on-cmds-state = \"",             "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelOffCommand',               \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,panel-off-cmds = ",                    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelOffCommandState',          \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\tlcd-kit,panel-off-cmds-state = \"",            "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelBacklightCommand',         \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,backlight-cmds = ",                    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelBacklightCommandState',    \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\tlcd-kit,backlight-cmds-state = \"",            "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelTpColorCommand',         \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,tp-color-cmds = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelDisplayOnEffectCommand',         \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,effect-on-cmds = ",                    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCabcOffMode',              \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,cabc-off-cmds = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCabcOffModeState',         \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\tlcd-kit,cabc-off-cmds-state = \"",             "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelCabcUiMode',               \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,cabc-ui-cmds = ",                      ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCabcUiModeState',          \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\tlcd-kit,cabc-ui-cmds-state = \"",              "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelCabcStillMode',            \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,cabc-still-cmds = ",                   ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCabcStillModeState',       \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\tlcd-kit,cabc-still-cmds-state = \"",           "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelCabcMovingMode',           \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,cabc-moving-cmds = ",                  ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCabcMovingModeState',      \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\tlcd-kit,cabc-moving-cmds-state = \"",          "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelRgbwSet1Mode',				\&parse_multi_xml,
        \&parser_hex_order, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-mode1-cmds = ",			        ";\n"				  ],
        ['/hwlcd/PanelEntry/PanelRgbwSet1ModeState', 		\&parse_multi_xml,
        \&parser_cmd_state, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-mode1-cmds-state = \"",	        "\";\n" 			  ],
        ['/hwlcd/PanelEntry/PanelRgbwSet2Mode',				\&parse_multi_xml,
        \&parser_hex_order, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-mode2-cmds = ",		        	";\n"				  ],
        ['/hwlcd/PanelEntry/PanelRgbwSet2ModeState',			\&parse_multi_xml,
        \&parser_cmd_state, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-mode2-cmds-state = \"",           "\";\n" 			  ],
        ['/hwlcd/PanelEntry/PanelRgbwSet3Mode',			\&parse_multi_xml,
        \&parser_hex_order, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-mode3-cmds = ",	             	";\n"				  ],
        ['/hwlcd/PanelEntry/PanelRgbwSet3ModeState',		\&parse_multi_xml,
        \&parser_cmd_state, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-mode3-cmds-state = \"",           "\";\n" 			  ],
        ['/hwlcd/PanelEntry/PanelRgbwSet4Mode',			\&parse_multi_xml,
        \&parser_hex_order, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-mode4-cmds = ",		            ";\n"				  ],
        ['/hwlcd/PanelEntry/PanelRgbwSet4ModeState',		\&parse_multi_xml,
        \&parser_cmd_state, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-mode4-cmds-state = \"",           "\";\n"	     		  ],
        ['/hwlcd/PanelEntry/PanelRgbwBacklightCommand',			\&parse_multi_xml,
        \&parser_hex_order, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-backlight-cmds = ",            	";\n"			      ],
        ['/hwlcd/PanelEntry/PanelRgbwBacklightCommandState',		\&parse_multi_xml,
        \&parser_cmd_state, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-backlight-cmds-state = \"",       "\";\n"		     	  ],
        ['/hwlcd/PanelEntry/PanelRgbwPixelgainlimitCommand', 		\&parse_multi_xml,
        \&parser_hex_order, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-pixel-gain-limit-cmds = ",      	";\n"				  ],
        ['/hwlcd/PanelEntry/PanelRgbwPixelgainlimitCommandState',		\&parse_multi_xml,
        \&parser_cmd_state, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-pixel-gain-limit-cmds-state = \"","\";\n"	              ],
        ['/hwlcd/PanelEntry/PanelRgbwSaturationcontrolCommand', 		\&parse_multi_xml,
        \&parser_hex_order, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-saturation-cmds = ", 	            ";\n"				  ],
        ['/hwlcd/PanelEntry/PanelRgbwSaturationcontrolCommandState',		\&parse_multi_xml,
        \&parser_cmd_state, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-saturation-cmds-state = \"",      "\";\n"	              ],
        ['/hwlcd/PanelEntry/PanelRgbwFramegainlimitCommand', 		\&parse_multi_xml,
        \&parser_hex_order, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-frame-gain-limit-cmds = ",     	";\n"				  ],
        ['/hwlcd/PanelEntry/PanelRgbwFramegainlimitCommandState',		\&parse_multi_xml,
        \&parser_cmd_state, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-frame-gain-limit-cmds-state = \"","\";\n"	              ],
        ['/hwlcd/PanelEntry/PanelRgbwFramegainspeedCommand', 		\&parse_multi_xml,
        \&parser_hex_order, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-frame-gain-speed-cmds = ",    	";\n"				  ],
        ['/hwlcd/PanelEntry/PanelRgbwFramegainspeedCommandState',		\&parse_multi_xml,
        \&parser_cmd_state, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-frame-gain-speed-cmds-state = \"","\";\n"		          ],
        ['/hwlcd/PanelEntry/PanelRgbwColordistortionCommand', 		\&parse_multi_xml,
        \&parser_hex_order, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-color-distor-allowance-cmds = ", 	";\n"				  ],
        ['/hwlcd/PanelEntry/PanelRgbwColordistortionCommandState',		\&parse_multi_xml,
        \&parser_cmd_state, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-color-distor-allowance-cmds-state = \"",  "\";\n"	      ],
        ['/hwlcd/PanelEntry/PanelRgbwPixelgainspeedCommand', 		\&parse_multi_xml,
        \&parser_hex_order, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-pixel-gain-speed-cmds = ", 	    ";\n"				  ],
        ['/hwlcd/PanelEntry/PanelRgbwPixelgainspeedCommandState',		\&parse_multi_xml,
        \&parser_cmd_state, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-pixel-gain-speed-cmds-state = \"","\";\n"	              ],
        ['/hwlcd/PanelEntry/PanelRgbwPwmdutygainCommand', 		\&parse_multi_xml,
        \&parser_hex_order, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-pwm-gain-cmds = ", 	            ";\n"				  ],
        ['/hwlcd/PanelEntry/PanelRgbwPwmdutygainCommandState',		\&parse_multi_xml,
        \&parser_cmd_state, 								"-f",		 'comm',
        "\t\tlcd-kit,rgbw-pwm-gain-cmds-state = \"",        "\";\n"	              ],
        ['/hwlcd/PanelEntry/PanelCeOffMode',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,ce-off-cmds = ",                       ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCeSrgbMode',               \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,ce-srgb-cmds = ",                      ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCeUserMode',               \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,ce-user-cmds = ",                      ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCeVividMode',              \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,ce-vivid-cmds = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelEsdRegCommand',            \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,esd-reg-cmds = ",                      ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelEsdRegCommandState',       \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\tlcd-kit,esd-reg-cmds-state = \"",              "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelEsdValue',                 \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,esd-value = ",                         ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCheckRegCommand',          \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,check-reg-cmds = ",                    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCheckRegCommandState',     \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\tlcd-kit,check-reg-cmds-state = \"",            "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelCheckRegValue',            \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,check-reg-value = ",                   ";\n"                 ],
        ['/hwlcd/PanelEntry/Barcode2DCommand', \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,barcode-2d-cmds = ",                   ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelProjectIDCommand', \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,project-id-cmds = ",                   ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelGammaCorrectReg',          \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,gamma-cmds = ",                        ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelColorCoordinateCommand', \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,color-coordinate-cmds = ",	            ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelConsistencyInfoCommand', \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,consistency-cmds = ",                  ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCurrentDetectCommand',     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,current-det-cmds = ",                  ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCurrentDetectValue',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,current-det-value =  ",                ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelLvDetectCommand',          \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,lv-det-cmds = ",                       ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelLvDetectValue',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,lv-det-value =  ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelChecksumEnableCommand',     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,checksum-enable-cmds = ",              ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelChecksumDisableCommand',     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,checksum-disable-cmds = ",             ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelChecksumCommand',          \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,checksum-cmds = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelChecksumValue',            \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,checksum-value = ",                    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelDirtyRegionCommand',     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,dirty-region-cmds = ",                 ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelFpsToThirtyCommand',           \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,fps-to-30-cmds = ",                    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelFpsToSixtyCommand',           \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,fps-to-60-cmds = ",                    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelDfrEnableCommand',         \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,fps-dfr-enable-cmds = ",               ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelDfrDisableCommand',        \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\tlcd-kit,fps-dfr-disable-cmds = ",              ";\n"                 ],
        #the parameter of Qcom platform
        ['/hwlcd/PanelEntry/ColorFormat',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,dsi-bpp = <",                        ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelCmdType',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,panel-cmd-type = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/PixelPacking',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,pixel-packing = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/UnderFlowColor',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,underflow-color = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/BorderColor',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,border-color = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelOrientation',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,panel-orientation = <",              ">;\n"                ],
        ['/hwlcd/PanelEntry/BLMaxLevel',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,brightness-max-level = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/BLMinLevel',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,bl-min-level = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/BLMaxLevel',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,bl-max-level = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/InterleaveMode',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,interleave-mode = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/TECheckEnable',                 \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,te-check-enable;\n",                 ""                    ],
        ['/hwlcd/PanelEntry/LcdSleepResetEnable',           \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,down-reset-enable;\n",               ""                    ],
        ['/hwlcd/PanelEntry/TEUsingTEPin',                  \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,te-using-te-pin;\n",                 ""                    ],
        ['/hwlcd/PanelEntry/HSyncPulse',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,h-sync-pulse = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/HFPPowerMode',                  \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,hfp-power-mode = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/HSAPowerMode',                  \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,hsa-power-mode = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/HBPPowerMode',                  \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,hbp-power-mode = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/LastLineInterleave',            \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,last-line-interleave = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/BLLPPowerMode',                 \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,bllp-power-mode;\n",                 ""                    ],
        ['/hwlcd/PanelEntry/BLLPEOFPowerMode',              \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,bllp-eof-power-mode;\n",             ""                    ],
        ['/hwlcd/PanelEntry/TrafficMode',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,traffic-mode = ",                    ";\n"                 ],
        ['/hwlcd/PanelEntry/TEDCSCommand',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,te-dcs-command = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/WrMemContinue',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,wr-mem-continue = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/WrMemStart',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,wr-mem-start = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/TEPinSelect',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,te-pin-select = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/DSIVirtualChannelId',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,virtual-channel-id = <",             ">;\n"                ],
        ['/hwlcd/PanelEntry/ColorOrder',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,color-order = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/Lane0State',                    \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,lane-0-state;\n",                    ""                    ],
        ['/hwlcd/PanelEntry/Lane1State',                    \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,lane-1-state;\n",                    ""                    ],
        ['/hwlcd/PanelEntry/Lane2State',                    \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,lane-2-state;\n",                    ""                    ],
        ['/hwlcd/PanelEntry/Lane3State',                    \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,lane-3-state;\n",                    ""                    ],
        ['/hwlcd/PanelEntry/HLeftBorder',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,h-left-border = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/HRightBorder',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,h-right-border = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/VTopBorder',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,v-top-border = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/VBottomBorder',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,v-bottom-border = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelFrameRate',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,panel-framerate = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelClockrate',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,panel-clockrate = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelTimings',                  \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'qcom',
        "\t\tlcd-kit,panel-timings = ",                   ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelTimingsV2',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'qcom',
        "\t\tlcd-kit,panel-timings-phy-v2 = ",            ";\n"                 ],
        ['/hwlcd/PanelEntry/TClkPre',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,t-clk-pre = <",                      ">;\n"                ],
        ['/hwlcd/PanelEntry/TClkPost',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,t-clk-post = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/RxEotIgnore',                   \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,rx-eot-ignore = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/TxEotAppend',                   \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,tx-eot-append",                      ";\n"                 ],
        ['/hwlcd/PanelEntry/DSIStream',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,stream = <",                         ">;\n"                ],
        ['/hwlcd/PanelEntry/ModSelGpioState',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,mode-sel-gpio-state = <",            ">;\n"                ],
        ['/hwlcd/PanelEntry/TransferTimeUs',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,mdp-transfer-time-us = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/Lp11InitFlag',                  \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,lp11-init;\n",                       ""                    ],
        ['/hwlcd/PanelEntry/PostInitDelay',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,post-init-delay = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/DSIMDPTrigger',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,mdp-trigger = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/DSIDMATrigger',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,dma-trigger = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/AdjTimerWakeupMs',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,adjust-timer-wakeup-ms = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/ForceClkLaneHs',                \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,force-clock-lane-hs",                ";\n"                 ],
        ['/hwlcd/PanelEntry/LcdDbaPanel',                   \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tlcd-kit,dba-panel",                          ";\n"                 ],
        ['/hwlcd/PanelEntry/LcdBridgeName',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,bridge-name = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/BLPMICControlType',             \&parse_multi_xml,
        \&parser_pmic_ctrl,                                 "-f",        'qcom',
        "\t\tlcd-kit,bl-pmic-control-type = \"",          "\";\n"               ],
        ['/hwlcd/PanelEntry/SupplyEntries',                 \&parse_multi_xml,
        \&apply_patten,                                     "-f",        'qcom',
        "\t\tqcom,panel-supply-entries = <&",               ">;\n"                     ],
        ['/hwlcd/PanelEntry/DSILaneMap',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,lane-map = ",                        ";\n"                 ],
        ['/hwlcd/PanelEntry/DelayBeBL',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,delay-before-bl = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiRegulatorMode',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,mipi-regulator-mode = <",            ">;\n"                ],
        ['/hwlcd/PanelEntry/UlpsEnabled',             		\&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tqcom,ulps-enabled",                            ";\n"                      ],
        ['/hwlcd/PanelEntry/SuspendUlpsEnabled',             \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tqcom,suspend-ulps-enabled",                    ";\n"                      ],
        ['/hwlcd/PanelEntry/GpioBlEn',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,bl-en-gpio = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/BlChipInit',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,bl-chip-init = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/DelayAfRstOff',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,delay-af-rst-off = <",               ">;\n"                ],
        ['/hwlcd/PanelEntry/DelayAfBLICInit',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,delay-af-blic-init = <",             ">;\n"                ],
        ['/hwlcd/PanelEntry/BlLevelLimitPercent',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,bl-level-limit-percent = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelEsdRegCurIcCommand',       \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'qcom',
        "\t\tlcd-kit,panel-esd-reg-curic-command = ",     ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelEsdRegCurIcCommandState',  \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'qcom',
        "\t\tlcd-kit,panel-esd-reg-curic-command-state =\"",     "\";\n"        ],
        ['/hwlcd/PanelEntry/PanelEsdRegOriIcCommand',       \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'qcom',
        "\t\tlcd-kit,panel-esd-reg-oriic-command = ",     ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelEsdRegOriIcCommandState',  \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'qcom',
        "\t\tlcd-kit,panel-esd-reg-oriic-command-state =\"",     "\";\n"        ],
        ['/hwlcd/PanelEntry/UseSecondIcForEsd',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,use-second-ic-for-esd = <",          ">;\n"                ],
        ['/hwlcd/PanelEntry/EsdCheckNum',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,esd-check-num = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/Lp8556BlChannelConfig',         \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,lp8556-bl-channel-config = <",       ">;\n"                ],
        ['/hwlcd/PanelEntry/Lp8556BlMaxVboostSelect',       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\tlcd-kit,lp8556-bl-max-vboost-select = <",    ">;\n"                ],
        #the parameter of hisi platform
        ['/hwlcd/PanelEntry/PanelOrientation',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-orientation = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelBpp',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-bpp = <",                      ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelBgrfmt',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-bgr-fmt = <",                   ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelCmdType',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-cmd-type = <",                 ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelPxlClk',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-pxl-clk = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelPxlClkDiv',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-pxl-clk-div = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelVsynCtrType',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-vsyn-ctr-type = <",            ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelIfbcType',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-ifbc-type = <",                ">;\n"                       ],
        ['/hwlcd/PanelEntry/VesaSliceWidth',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,vesa-slice-width = <",               ">;\n"                       ],
        ['/hwlcd/PanelEntry/VesaSliceHeight',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,vesa-slice-height = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelFrcEnable',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-frc-enable = <",               ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelEsdSkipMipiCheck',         \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-esd-skip-mipi-check = <",      ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelHisiEsdSupport',               	 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,esd-support = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelFpsUpdtSupport',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,fps-support = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/BacklightOrder',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,backlight-order = <",                ">;\n"                       ],
        ['/hwlcd/PanelEntry/BacklightPrecision',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,backlight-precision = <",            ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelQuicklySleepOutSupport',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,quickly-sleep-out-support = <",      ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelQuicklySleepOutInterval',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,quickly-sleep-out-interval = <",     ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelEsdSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,esd-support = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelProjectIdSupport',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,project-id-support = <",             ">;\n"                       ],
        ['/hwlcd/PanelEntry/OemInfoSupport',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,oem-info-support = <",               ">;\n"                       ],
        ['/hwlcd/PanelEntry/OemBarcode2DSupport',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,oem-barcode-2d-support = <",         ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelDirtyRegionSupport',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,dirty-region-support = <",           ">;\n"                       ],
        ['/hwlcd/PanelEntry/DirtyLeftAlign',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,dirty-left-align = <",               ">;\n"                       ],
        ['/hwlcd/PanelEntry/DirtyRightAlign',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,dirty-right-align = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/DirtyTopAlign',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,dirty-top-align = <",                ">;\n"                       ],
        ['/hwlcd/PanelEntry/DirtyBottAlign',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,dirty-bott-align = <",               ">;\n"                       ],
        ['/hwlcd/PanelEntry/DirtyWidthAlign',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,dirty-width-align = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/DirtyHeightAlign',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,dirty-height-align = <",             ">;\n"                       ],
        ['/hwlcd/PanelEntry/DirtyWidthMin',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,dirty-width-min = <",                ">;\n"                       ],
        ['/hwlcd/PanelEntry/DirtyHeightMin',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,dirty-height-min = <",               ">;\n"                       ],
        ['/hwlcd/PanelEntry/DirtyTopStart',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,dirty-top-start = <",                ">;\n"                       ],
        ['/hwlcd/PanelEntry/DirtyBottStart',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,dirty-bott-start = <",               ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelBlType' ,                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-bl-type = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelBlmin' ,                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-bl-min = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelBlmax',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-bl-max = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelBlDef',                    \&parse_multi_xml,      
        'need_nothing_here',                                "-n",        'hisi',     
        "\t\tlcd-kit,panel-bl-def = <",                   ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelBlPwmPreciType',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-bl-pwm-preci-type = <",        ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelBlIcCtrlType',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-bl-ic-ctrl-type = <",         ">;\n"                        ],
        ['/hwlcd/PanelEntry/HBackPorch',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,h-back-porch = <",                   ">;\n"                       ],
        ['/hwlcd/PanelEntry/HFrontPorch',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,h-front-porch = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/HPulseWidth',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,h-pulse-width = <",                  ">;\n"                       ],      
        ['/hwlcd/PanelEntry/VBackPorch',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,v-back-porch = <",                   ">;\n"                       ],
        ['/hwlcd/PanelEntry/VFrontPorch',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,v-front-porch = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/VPulseWidth',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,v-pulse-width = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/LdiHsyncPlr',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,ldi-hsync-plr = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/LdiVsyncPlr',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,ldi-vsync-plr = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/LdiPixelClkPlr',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,ldi-pixel-clk-plr = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/LdiDataEnPlr',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,ldi-data-en-plr = <",                ">;\n"                       ],
        ['/hwlcd/PanelEntry/LdiDpiAOverlapSize',            \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,ldi-dpi-a-overlap-size = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/LdiDpiBOverlapSize',            \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,ldi-dpi-b-overlap-size = <",  ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiDsiUptSupport',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-dsi-upt-support = <",           ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiLaneNums',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-lane-nums = <",                 ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiColorMode',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-color-mode = <",                ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiVc',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-vc = <",                        ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiDsiBitClk',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-dsi-bit-clk = <",               ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiBurstMode',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-burst-mode = <",                ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiMaxTxEscClk',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-max-tx-esc-clk = <",            ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiDsiBitClkValA',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-dsi-bit-clk-val1 = <",          ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiDsiBitClkValB',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-dsi-bit-clk-val2 = <",          ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiDsiBitClkValC',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-dsi-bit-clk-val3 = <",          ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiDsiBitClkValD',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-dsi-bit-clk-val4 = <",          ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiDsiBitClkValE',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-dsi-bit-clk-val5 = <",          ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiDsiBitClkUpt',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-dsi-bit-clk-upt = <",           ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiRgVcmAdjust',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-rg-vrefsel-vcm-adjust = <",     ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiNonContinueEnable',         \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-non-continue-enable = <",       ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiClkPostAdjust',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-clk-post-adjust = <",           ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiLp11Flag',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-lp11-flag = <",                 ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiPhyUpdate',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-phy-update = <",                ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiClkPreAdjust',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-clk-pre-adjust = <",            ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiClkTHsPrepareAdjust',       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-clk-t-hs-prepare-adjust = <",   ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiClkTLpxAdjust',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-clk-t-lpx-adjust = <",          ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiClkTHsTrailAdjust',         \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-clk-t-hs-trail-adjust = <",     ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiClkTHsExitAdjust',          \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-clk-t-hs-exit-adjust = <",      ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiClkTHsZeroAdjust',          \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-clk-t-hs-zero-adjust = <",      ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiDataTHsTrialAdjust',          \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-data-t-hs-trial-adjust = <",    ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiDataTlpxAdjust',          \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-data-t-lpx-adjust = <",         ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiPhyMode',          \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-phy-mode = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/MipiHsWrToTime',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,mipi-hs-wr-to-time = <",             ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelInversionSupport',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,inversion-support = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelScanSupport',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,scan-support = <",                   ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelCheckRegSupport',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,check-reg-support = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelChecksumSupport',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,checksum-support = <",               ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelCurrentDetectSupport',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,current-det-support = <",            ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelVoltageDetectSupport',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,lv-det-support = <",                 ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelPtTestSupport',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,pt-support = <",                     ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelHkadcSupport',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,hkadc-support = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/LdoCheckSupport',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,ldo-check-support = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/LdoCheckName',                      \&parse_multi_xml,
        \&pin_name_trans,                                   "-f",        'hisi',
        "\t\tlcd-kit,ldo-check-name = ",                   ";\n"                       ],
        ['/hwlcd/PanelEntry/LdoCheckChannel',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,ldo-check-channel = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/LdoCheckThreshold',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,ldo-check-threshold = <",            ">;\n"                       ],
        ['/hwlcd/PanelEntry/Status',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tstatus = ",                                   ";\n"                       ],
        ['/hwlcd/PanelEntry/IOVccRegulator',                      \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tiovcc-supply = <",                            ">;\n"                      ],
        ['/hwlcd/PanelEntry/VddRegulator',                      \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tvdd-supply = <",                              ">;\n"                      ],
        ['/hwlcd/PanelEntry/VciRegulator',                      \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tvci-supply = <",                              ">;\n"                      ],
        ['/hwlcd/PanelEntry/BacklightRegulator',                      \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tbacklight-supply = <",                        ">;\n"                      ],
        ['/hwlcd/PanelEntry/BiasRegulator',                      \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tbias-supply = <",                             ">;\n"                      ],
        ['/hwlcd/PanelEntry/VspRegulator',                      \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tvsp-supply = <",                              ">;\n"                      ],
        ['/hwlcd/PanelEntry/VsnRegulator',                      \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tvsn-supply = <",                              ">;\n"                      ],
        ['/hwlcd/PanelEntry/LcdVci',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,lcd-vci = ",                          ";\n"                       ],
        ['/hwlcd/PanelEntry/LcdIovcc',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,lcd-iovcc = ",                        ";\n"                       ],
        ['/hwlcd/PanelEntry/LcdVdd',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,lcd-vdd = ",                          ";\n"                       ],
        ['/hwlcd/PanelEntry/LcdVsp',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,lcd-vsp = ",                          ";\n"                       ],
        ['/hwlcd/PanelEntry/LcdVsn',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,lcd-vsn = ",                          ";\n"                       ],
        ['/hwlcd/PanelEntry/LcdReset',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,lcd-reset = ",                        ";\n"                       ],
        ['/hwlcd/PanelEntry/TpReset',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,tp-reset = ",                         ";\n"                       ],
        ['/hwlcd/PanelEntry/LcdTe0',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,lcd-te0 = ",                          ";\n"                       ],
        ['/hwlcd/PanelEntry/LcdBacklight',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,lcd-backlight = ",            ";\n"                       ],
        ['/hwlcd/PanelEntry/PowerOnStage',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,power-on-stage = ",                   ";\n"                       ],
        ['/hwlcd/PanelEntry/LPOnStage',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,lp-on-stage = ",                      ";\n"                       ],
        ['/hwlcd/PanelEntry/HSOnStage',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,hs-on-stage = ",                      ";\n"                       ],
        ['/hwlcd/PanelEntry/HSOffStage',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,hs-off-stage = ",                     ";\n"                       ],
        ['/hwlcd/PanelEntry/LPOffStage',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,lp-off-stage = ",                     ";\n"                       ],
        ['/hwlcd/PanelEntry/PowerOffStage',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'hisi',
        "\t\tlcd-kit,power-off-stage = ",                  ";\n"                       ],
        ['/hwlcd/PanelEntry/TpColorSupport',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,tp-color-support = <",               ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelBlMaxnit',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,panel-bl-max-nit = <",               ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelCabcSupport',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,cabc-support = <",                   ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelRgbwSupport',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,rgbw-support = <",                   ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelAclCtrlSupport',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,acl-support = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelHbmCtrlSupport',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,hbm-support = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelVrSupport',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,vr-support = <",                     ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelDynamicGammaSupport',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,gamma-cal-support = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblSupport',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-support = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblStrenLimit',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-stren-limit = <",                ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblCalA',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-cal-a = <",                      ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblCalB',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-cal-b = <",                      ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblCalC',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-cal-c = <",                      ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblCalD',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-cal-d = <",                      ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblTfCtl',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-tf-ctl = <",                     ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblBlmin',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-bl-min = <",                     ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblBlmax',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-bl-max = <",                     ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblBlScale',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-bl-scale = <",                   ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblAmLightMin',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-am-light-min = <",               ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblFilterA',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-filter-a = <",                   ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblFilterB',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-filter-b = <",                   ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblLogoLeft',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-logo-left = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblLogoTop',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-logo-top = <",                   ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblVarianceIntensitySpace',     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-variance-intensity-space = <",   ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblSlopeMax',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-slope-max = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/SblSlopeMin',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,sbl-slope-min = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelBrightnessColorUniformSupport', \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,brightness-color-uniform-support = <",">;\n"                      ],
        ['/hwlcd/PanelEntry/GammaSupport',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,gamma-support = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/CeSupport',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,ce-support = <",                     ">;\n"                       ],
        ['/hwlcd/PanelEntry/PanelDisplayOnEffectSupport',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,effect-on-support = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/GmpSupport',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,gmp-support = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/ColorTempSupport',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,color-temp-support = <",             ">;\n"                       ],
        ['/hwlcd/PanelEntry/ColorTempRectifySupport',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,color-temp-rectify-support = <",     ">;\n"                       ],
        ['/hwlcd/PanelEntry/HiaceSupport',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,hiace-support = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/IGlobalHistBlackPos',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,iglobal-hist-black-pos = <",         ">;\n"                       ],
        ['/hwlcd/PanelEntry/IGlobalHistWhitePos',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,iglobal-hist-white-pos = <",         ">;\n"                       ],
        ['/hwlcd/PanelEntry/IGlobalHistBlackWeight',        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,iglobal-hist-black-weight = <",      ">;\n"                       ],
        ['/hwlcd/PanelEntry/IGlobalHistWhiteWeight',        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,iglobal-hist-white-weight = <",      ">;\n"                       ],
        ['/hwlcd/PanelEntry/IGlobalHistZeroCutRatio',       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,iglobal-hist-zero-cut-ratio = <",    ">;\n"                       ],
        ['/hwlcd/PanelEntry/IGlobalHistSlopeCutRatio',        \&parse_multi_xml,
        'need_nothing_here',                                 "-n",        'hisi',
        "\t\tlcd-kit,iglobal-hist-slope-cut-ratio = <",   ">;\n"                       ],
        ['/hwlcd/PanelEntry/IMaxLcdLuminance',               \&parse_multi_xml,
        'need_nothing_here',                                 "-n",        'hisi',
        "\t\tlcd-kit,imax-lcd-luminance = <",             ">;\n"                       ],
        ['/hwlcd/PanelEntry/IMinLcdLuminance',               \&parse_multi_xml,
        'need_nothing_here',                                 "-n",        'hisi',
        "\t\tlcd-kit,imin-lcd-luminance = <",             ">;\n"                       ],
        ['/hwlcd/PanelEntry/XccSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,xcc-support = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/ComformModeSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,comform-mode-support = <",           ">;\n"                       ],
        ['/hwlcd/PanelEntry/CinemaModeSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,cinema-mode-support = <",            ">;\n"                       ],
        ['/hwlcd/PanelEntry/EffectColorSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,effect-color-support = <",           ">;\n"                       ],
        ['/hwlcd/PanelEntry/PrefixCeSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,prefix-ce-support = <",              ">;\n"                       ],
        ['/hwlcd/PanelEntry/Arsr1pSharpnessSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,arsr1p-sharpness-support = <",       ">;\n"                       ],
        ['/hwlcd/PanelEntry/PrefixSharpOneDSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,prefix-sharp-1D-support = <",        ">;\n"                       ],
        ['/hwlcd/PanelEntry/PrefixSharpTwoDSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,prefix-sharp-2D-support = <",        ">;\n"                       ],
        ['/hwlcd/PanelEntry/SmartColorModeSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,smart-color-mode-support = <",       ">;\n"                       ],
        ['/hwlcd/PanelEntry/ColorTempRectifyR',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,color-temp-rectify-r = <",           ">;\n"                       ],
        ['/hwlcd/PanelEntry/ColorTempRectifyG',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,color-temp-rectify-g = <",           ">;\n"                       ],
        ['/hwlcd/PanelEntry/ColorTempRectifyB',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,color-temp-rectify-b = <",           ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/AcmSupport',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,acm-support = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/AcmCeSupport',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,acm-ce-support = <",                 ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/AcmValidNum',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,acm-valid-num = <",                  ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_hh0',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_hh0 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_lh0',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_lh0 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_hh1',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_hh1 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_lh1',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_lh1 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_hh2',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_hh2 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_lh2',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_lh2 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_hh3',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_hh3 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_lh3',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_lh3 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_hh4',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_hh4 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_lh4',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_lh4 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_hh5',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_hh5 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_lh5',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_lh5 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_hh6',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_hh6 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_lh6',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_lh6 = <",                          ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_hh0',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_hh0 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_lh0',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_lh0 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_hh1',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_hh1 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_lh1',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_lh1 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_hh2',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_hh2 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_lh2',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_lh2 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_hh3',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_hh3 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_lh3',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_lh3 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_hh4',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_hh4 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_lh4',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_lh4 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_hh5',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_hh5 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_lh5',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_lh5 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_hh6',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_hh6 = <",                    ">;\n"                       ],
        ['/hwlcd/PanelEntry/acm/r_video_lh6',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tlcd-kit,r_video_lh6 = <",                    ">;\n"                       ]
        );
my @dtsi_lcd_bias_ic_attrs = (
    ["BiasICName",                "-n",  "",  "",  ""],
	["BiasICType",                "-n",   0,  "lcdkit-bias-type = <",  ">;\n"],
	["BiasICVposReg",             "-n",   0,  "lcdkit-bias-vpos-reg = <",  ">;\n"],
	["BiasICVnegReg",             "-n",   0,  "lcdkit-bias-vneg-reg = <",  ">;\n"],
	["BiasICVposVal",             "-n",   0,  "lcdkit-bias-vpos-val = <",  ">;\n"],
	["BiasICVnegVal",             "-n",   0,  "lcdkit-bias-vneg-val = <",  ">;\n"],
	["BiasICVposMask",            "-n",   0,  "lcdkit-bias-vpos-mask = <",  ">;\n"],
	["BiasICVnegMask",            "-n",   0,  "lcdkit-bias-vneg-mask = <",  ">;\n"],
	["BiasICStateReg",            "-n",   0,  "lcdkit-bias-state-reg = <",  ">;\n"],
	["BiasICStateVal",            "-n",   0,  "lcdkit-bias-state-val = <",  ">;\n"],
	["BiasICStateMask",           "-n",   0,  "lcdkit-bias-state-mask = <",  ">;\n"]
);

for ($count = 0; $count < @dtsi_property_strings; $count++){
    if (($platform ne $dtsi_property_strings[$count][4])
     && ('comm' ne $dtsi_property_strings[$count][4]))
    {
        next;
    }
    
    if ($dtsi_property_strings[$count][0] eq 'need_nothing_here'){
        print $panel_dtsi_file $dtsi_property_strings[$count][5];
        next;
    }

    if ($dtsi_property_strings[$count][0] eq 'depond-on')
    {
        my $parser_tmp_str = $dtsi_property_strings[$count][1]->($dtsi_property_strings[$count][2]);
        if ($parser_tmp_str ne $parse_error_string){
            print $panel_dtsi_file $dtsi_property_strings[$count][5];
        }
        next;
    }

    my $parser_tmp_str = $dtsi_property_strings[$count][1]->($dtsi_property_strings[$count][0]);
    if ($parser_tmp_str eq $parse_error_string)    {
        debug_print("parse $dtsi_property_strings[$count][0] get a error string!\n");
        next;
    }

    if ($dtsi_property_strings[$count][3] eq '-f')    {
        $parser_tmp_str = $dtsi_property_strings[$count][2]->($parser_tmp_str);
        if ($parser_tmp_str eq $parse_error_string)    {
            debug_print("parse $dtsi_property_strings[$count][0] string trans error!\n");
            next;
        }
    }
    
    if ($dtsi_property_strings[$count][3] eq "eq")    {
        if ($parser_tmp_str ne $dtsi_property_strings[$count][2])    {
            next;
        }
        
        $parser_tmp_str = '';
    }
    
    if ($dtsi_property_strings[$count][3] eq "ne")    {
        if ($parser_tmp_str eq $dtsi_property_strings[$count][2])    {
            next;
        }
        
        $parser_tmp_str = '';
    }

    $parser_tmp_str = $dtsi_property_strings[$count][5].$parser_tmp_str.$dtsi_property_strings[$count][6];
    print $panel_dtsi_file $parser_tmp_str;
}
my @dtsi_lcd_backlight_ic_attrs = (
    ["BacklightICName",                "-n",    "",  "",  ""],
    ["BacklightICLevel",               "-n",     0,  "lcdkit-bl-ic-level = <", ">;\n"],
    ["BacklightICKernelBlCtrlMode",    "-n",     0,  "lcdkit-bl-ic-ctrl-mode = <", ">;\n"],
    ["BacklightICType",                "-n",     0,  "lcdkit-bl-ic-type = <", ">;\n"],
    ["BacklightICBeforeInitDelay",     "-n",     0,  "lcdkit-bl-ic-before-init-delay = <", ">;\n"],
    ["BacklightICInitDelay",           "-n",     0,  "lcdkit-bl-ic-init-delay = <", ">;\n"],
    ["BacklightICOVPCheck",            "-n",     0,  "lcdkit-bl-ic-ovp-check = <", ">;\n"],
    ["BacklightICNoLcdOVPCheck",       "-n",     0,  "lcdkit-bl-ic-fake-lcd-ovp-check = <", ">;\n"],
    ["BacklightICKernelInitCMD",       "-f",     0,  "lcdkit-bl-ic-init-cmd = <", ">;\n"],
    ["BacklightICNumOfKernelInitCMD",  "-n",     0,  "lcdkit-bl-ic-num-of-init-cmd = <", ">;\n"],
    ["BacklightICBLLSBRegCMD",         "-f",     0,  "lcdkit-bl-ic-bl-lsb-reg-cmd = <", ">;\n"],
    ["BacklightICBLMSBRegCMD",         "-f",     0,  "lcdkit-bl-ic-bl-msb-reg-cmd = <", ">;\n"],
    ["BacklightICBLEnableCMD",         "-f",     0,  "lcdkit-bl-ic-bl-enable-cmd = <", ">;\n"],
    ["BacklightICBLDisableCMD",        "-f",     0,  "lcdkit-bl-ic-bl-disable-cmd = <", ">;\n"],
    ["BacklightICDeviceDisableCMD",    "-f",     0,  "lcdkit-bl-ic-disable-device-cmd = <", ">;\n"],
    ["BacklightICFaultFlagCMD",        "-f",     0,  "lcdkit-bl-ic-fault-flag-cmd = <", ">;\n"],
    ["BacklightICBiasEnableCMD",       "-f",     0,  "lcdkit-bl-ic-bias-disable-cmd = <", ">;\n"],
    ["BacklightICBiasDisableCMD",      "-f",     0,  "lcdkit-bl-ic-bias-enable-cmd = <", ">;\n"],
    ["BacklightICOpenShortTest",       "-n",     0,  "lcdkit-bl-ic-led-open-short-test = <", ">;\n"],
    ["BacklightICNumOfLed",            "-n",     0,  "lcdkit-bl-ic-num-of-led = <", ">;\n"],
    ["BacklightICBrtCtrlCMD",          "-f",     0,  "lcdkit-bl-ic-brt-ctrl-cmd = <", ">;\n"],
    ["BacklightICFaultCtrlCMD",        "-f",     0,  "lcdkit-bl-ic-fault-ctrl-cmd = <", ">;\n"]
);
my $lcd_bias_ic_base_tag = "hwlcd/HWBIASICLIST/BIASIC";
my $lcd_bias_ic_name_tag = "BiasICName";
create_dtsi_struct_array($lcd_bias_ic_base_tag, \@dtsi_lcd_bias_ic_attrs, \@lcd_xml_doc, $lcd_bias_ic_name_tag);
my $lcd_backlight_ic_base_tag = "hwlcd/HWBACKLIGHTCLIST/BACKLIGHTIC";
my $lcd_backlight_ic_name_tag = "BacklightICName";
create_dtsi_struct_array($lcd_backlight_ic_base_tag, \@dtsi_lcd_backlight_ic_attrs, \@lcd_xml_doc, $lcd_backlight_ic_name_tag);

sub create_dtsi_struct_array
{
	my $nodebase = shift;
	my $attr_list = shift;
	my @attr_list = @$attr_list;
	my $xml_doc_list = shift;
	my @xml_doc_list = @$xml_doc_list;
	my $ic_name_tag = shift;
	my $parser_string = "";
	my $ic_name = "";

    foreach my $xml_doc (@xml_doc_list) {

    for my $dest($xml_doc->findnodes($nodebase)) {
		for (my $tmp_count = 0; $tmp_count < @attr_list; $tmp_count++) {
			$list_entry = $dest->findvalue('./' . $attr_list[$tmp_count][0]);
			if($attr_list[$tmp_count][0] eq $ic_name_tag)
			{
			    if($list_entry eq '')
				{
				    $ic_name = "default";
				}
				else
				{
				    $list_entry=~ s/"//g;
					$ic_name = "\t\t" . $list_entry;
				}
				next;
			}
			if ($list_entry eq '')
			{
			    if($attr_list[$tmp_count][1] eq "-f")
			    {
			        $list_entry = '0x00, 0x00, 0x00, 0x00';
			    }
			    else
			    {
			        $list_entry = $attr_list[$tmp_count][2];
			    }
			}
			$list_entry=~ s/"//g;
			$list_entry=~ s/,//g;
			$parser_string .= $ic_name . "," . $attr_list[$tmp_count][3] . $list_entry . $attr_list[$tmp_count][4];
		}
    }
	}

    print $panel_dtsi_file $parser_string;
}
print $panel_dtsi_file create_dtsi_tail();

close($panel_dtsi_file);

exit_with_info($panel_file_name, 0);

sub parser_hex_order {  return parser_hex_order_base(shift, $platform);  }
sub parse_multi_xml  {  return parse_multi_xml_base(\@lcd_xml_doc, shift);  }
