/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*-------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = 1.1
 *-----------------------------------------------------------------------*/

#ifndef _PANEL_BKK_AL00AHN_VA_TXD_INX_NT36525_6P26_720P_VIDEO_H_

#define _PANEL_BKK_AL00AHN_VA_TXD_INX_NT36525_6P26_720P_VIDEO_H_
/*-----------------------------------------------------------------------*/
/* HEADER files                                                          */
/*-----------------------------------------------------------------------*/
#include "panel.h"

#include "lcdkit_bias_ic_common.h"

#include "lcd_bl.h"

/*-----------------------------------------------------------------------*/
/* Panel configuration                                                   */
/*-----------------------------------------------------------------------*/
static struct panel_config bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_panel_data = {
        "lcdkit_bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video", "dsi:0:", 
        "txd-inx-nt36525-6p26-720p-video", 10, 0, "DISPLAY_1", 
        0, 738350000, 60, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel resolution                                                      */
/*-----------------------------------------------------------------------*/
static struct panel_resolution bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_panel_res = {
        720, 1520, 63, 80, 10, 0, 8, 230, 2, 0, 0, 0, 2, 0, 0, 0, 0, 
        0 
};

/*-----------------------------------------------------------------------*/
/* Panel color information                                               */
/*-----------------------------------------------------------------------*/
static struct color_info bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_color = {
        24, 0, 0x00, 0, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel on/off command                                                  */
/*-----------------------------------------------------------------------*/
static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd0[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFF, 0x20, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd1[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFB, 0x01, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd2[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x01, 0x55, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd3[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x03, 0x55, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd4[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x05, 0xB1, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd5[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x07, 0x73, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd6[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x08, 0xCB, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd7[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0E, 0x91, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd8[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0F, 0x69, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd9[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x69, 0xA9, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd10[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x94, 0xC0, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd11[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x95, 0x13, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd12[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x96, 0x13, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd13[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFF, 0x24, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd14[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFB, 0x01, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd15[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xC5, 0x30, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd16[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x93, 0x08, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd17[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x94, 0x06, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd18[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x05, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd19[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x01, 0x08, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd20[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x02, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd21[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x03, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd22[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0D, 0x18, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd23[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0E, 0x19, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd24[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0F, 0x0C, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd25[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x10, 0x0D, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd26[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x11, 0x0E, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd27[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x12, 0x0F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd28[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x13, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd29[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x14, 0x11, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd30[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x15, 0x04, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd31[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x16, 0x05, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd32[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x17, 0x08, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd33[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x18, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd34[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x19, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd35[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x23, 0x18, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd36[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x24, 0x19, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd37[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x25, 0x0C, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd38[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x26, 0x0D, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd39[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x27, 0x0E, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd40[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x28, 0x0F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd41[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x29, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd42[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2A, 0x11, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd43[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2B, 0x04, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd44[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2F, 0x04, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd45[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x30, 0x32, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd46[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x33, 0x32, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd47[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x34, 0x04, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd48[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x37, 0x44, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd49[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x39, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd50[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3A, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd51[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3B, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd52[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3D, 0x52, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd53[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3F, 0x41, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd54[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x40, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd55[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x43, 0x41, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd56[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x44, 0x06, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd57[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x47, 0x44, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd58[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x49, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd59[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4A, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd60[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4B, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd61[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4C, 0x51, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd62[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4D, 0x12, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd63[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4E, 0x34, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd64[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4F, 0x56, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd65[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x51, 0x43, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd66[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x52, 0x21, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd67[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x53, 0x65, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd68[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x55, 0x43, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd69[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x56, 0x46, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd70[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5A, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd71[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5B, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd72[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5E, 0x06, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd73[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5F, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd74[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x92, 0xB7, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd75[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x76, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd76[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x77, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd77[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x78, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd78[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x79, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd79[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7A, 0x20, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd80[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7B, 0x3C, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd81[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7C, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd82[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7D, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd83[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7E, 0x08, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd84[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x87, 0x02, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd85[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xAB, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd86[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xAC, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd87[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xAD, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd88[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xAF, 0x04, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd89[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xB0, 0x05, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd90[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xB1, 0xB2, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd91[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x60, 0x80, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd92[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x61, 0x7C, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd93[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x64, 0x11, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd94[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFF, 0x25, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd95[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFB, 0x01, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd96[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x05, 0x04, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd97[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x07, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd98[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x08, 0x01, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd99[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0A, 0x82, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd100[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0B, 0x46, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd101[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0C, 0x01, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd102[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x17, 0x82, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd103[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x18, 0x06, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd104[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x19, 0x0F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd105[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x1E, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd106[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x1F, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd107[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x20, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd108[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x23, 0x05, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd109[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x24, 0xB2, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd110[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x25, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd111[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x26, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd112[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x27, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd113[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2A, 0x05, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd114[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2B, 0xB2, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd115[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2D, 0x80, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd116[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2F, 0x30, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd117[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x30, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd118[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x31, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd119[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x32, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd120[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x33, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd121[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x34, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd122[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x37, 0x05, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd123[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x38, 0xB2, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd124[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x40, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd125[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x41, 0x80, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd126[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x42, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd127[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x43, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd128[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x46, 0x05, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd129[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x47, 0xB2, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd130[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4A, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd131[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4B, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd132[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4C, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd133[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4D, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd134[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4E, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd135[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4F, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd136[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x50, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd137[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x53, 0x05, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd138[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x54, 0xB2, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd139[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x55, 0x05, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd140[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x56, 0xB2, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd141[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x58, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd142[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x59, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd143[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5A, 0x60, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd144[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5B, 0x80, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd145[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5C, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd146[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5D, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd147[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5E, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd148[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5F, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd149[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x60, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd150[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x61, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd151[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x62, 0x8F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd152[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x65, 0x05, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd153[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x66, 0xB2, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd154[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFF, 0x26, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd155[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFB, 0x01, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd156[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xA0, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd157[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFF, 0x27, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd158[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFB, 0x01, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd159[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x96, 0x03, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd160[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x97, 0x15, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd161[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x98, 0x11, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd162[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x99, 0x3F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd163[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x9B, 0x3F, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd164[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x9D, 0x25, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd165[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x9E, 0x55, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd166[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x9F, 0x05, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd167[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xAD, 0x25, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd168[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xAE, 0x55, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd169[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xAF, 0x05, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd170[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xB3, 0xC6, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd171[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xC0, 0x18, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd172[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xC1, 0xE4, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd173[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xC2, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd174[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xC3, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd175[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xC4, 0xE4, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd176[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xC5, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd177[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xC6, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd178[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xC7, 0x03, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd179[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFF, 0x23, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd180[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFB, 0x01, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd181[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x60, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd182[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x12, 0xAB, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd183[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x15, 0xF5, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd184[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x16, 0x0B, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd185[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFF, 0x20, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd186[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFB, 0x01, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd187[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB0, 0x00, 0x00, 0x00,
    0x13, 0x00, 0x32, 0x00,
    0x4C, 0x00, 0x62, 0x00,
    0x76, 0x00, 0x88, 0x00,
    0x98, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd188[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB1, 0x00, 0xA7, 0x00,
    0xD7, 0x00, 0xFD, 0x01,
    0x37, 0x01, 0x63, 0x01,
    0xA7, 0x01, 0xDE, 0x01,
    0xDF, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd189[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB2, 0x02, 0x10, 0x02,
    0x4B, 0x02, 0x71, 0x02,
    0xA8, 0x02, 0xCF, 0x02,
    0xFA, 0x03, 0x06, 0x03,
    0x1B, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd190[] = {
    0x0D, 0x00, 0x39, 0xC0,
    0xB3, 0x03, 0x35, 0x03,
    0x4B, 0x03, 0x64, 0x03,
    0x84, 0x03, 0xB3, 0x03,
    0xFF, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd191[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB4, 0x00, 0x00, 0x00,
    0x13, 0x00, 0x32, 0x00,
    0x4C, 0x00, 0x62, 0x00,
    0x76, 0x00, 0x88, 0x00,
    0x98, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd192[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB5, 0x00, 0xA7, 0x00,
    0xD7, 0x00, 0xFD, 0x01,
    0x37, 0x01, 0x63, 0x01,
    0xA7, 0x01, 0xDE, 0x01,
    0xDF, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd193[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB6, 0x02, 0x10, 0x02,
    0x4B, 0x02, 0x71, 0x02,
    0xA8, 0x02, 0xCF, 0x02,
    0xFA, 0x03, 0x06, 0x03,
    0x1B, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd194[] = {
    0x0D, 0x00, 0x39, 0xC0,
    0xB7, 0x03, 0x35, 0x03,
    0x4B, 0x03, 0x64, 0x03,
    0x84, 0x03, 0xB3, 0x03,
    0xFF, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd195[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB8, 0x00, 0x00, 0x00,
    0x13, 0x00, 0x32, 0x00,
    0x4C, 0x00, 0x62, 0x00,
    0x76, 0x00, 0x88, 0x00,
    0x98, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd196[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB9, 0x00, 0xA7, 0x00,
    0xD7, 0x00, 0xFD, 0x01,
    0x37, 0x01, 0x63, 0x01,
    0xA7, 0x01, 0xDE, 0x01,
    0xDF, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd197[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xBA, 0x02, 0x10, 0x02,
    0x4B, 0x02, 0x71, 0x02,
    0xA8, 0x02, 0xCF, 0x02,
    0xFA, 0x03, 0x06, 0x03,
    0x1B, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd198[] = {
    0x0D, 0x00, 0x39, 0xC0,
    0xBB, 0x03, 0x35, 0x03,
    0x4B, 0x03, 0x64, 0x03,
    0x84, 0x03, 0xB3, 0x03,
    0xFF, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd199[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFF, 0x21, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd200[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFB, 0x01, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd201[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB0, 0x00, 0x00, 0x00,
    0x13, 0x00, 0x32, 0x00,
    0x4C, 0x00, 0x62, 0x00,
    0x76, 0x00, 0x88, 0x00,
    0x98, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd202[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB1, 0x00, 0xA7, 0x00,
    0xD7, 0x00, 0xFD, 0x01,
    0x37, 0x01, 0x63, 0x01,
    0xA7, 0x01, 0xDE, 0x01,
    0xDF, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd203[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB2, 0x02, 0x10, 0x02,
    0x4B, 0x02, 0x71, 0x02,
    0xA8, 0x02, 0xCF, 0x02,
    0xFA, 0x03, 0x06, 0x03,
    0x1B, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd204[] = {
    0x0D, 0x00, 0x39, 0xC0,
    0xB3, 0x03, 0x35, 0x03,
    0x4B, 0x03, 0x64, 0x03,
    0x84, 0x03, 0xB3, 0x03,
    0xFF, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd205[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB4, 0x00, 0x00, 0x00,
    0x13, 0x00, 0x32, 0x00,
    0x4C, 0x00, 0x62, 0x00,
    0x76, 0x00, 0x88, 0x00,
    0x98, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd206[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB5, 0x00, 0xA7, 0x00,
    0xD7, 0x00, 0xFD, 0x01,
    0x37, 0x01, 0x63, 0x01,
    0xA7, 0x01, 0xDE, 0x01,
    0xDF, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd207[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB6, 0x02, 0x10, 0x02,
    0x4B, 0x02, 0x71, 0x02,
    0xA8, 0x02, 0xCF, 0x02,
    0xFA, 0x03, 0x06, 0x03,
    0x1B, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd208[] = {
    0x0D, 0x00, 0x39, 0xC0,
    0xB7, 0x03, 0x35, 0x03,
    0x4B, 0x03, 0x64, 0x03,
    0x84, 0x03, 0xB3, 0x03,
    0xFF, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd209[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB8, 0x00, 0x00, 0x00,
    0x13, 0x00, 0x32, 0x00,
    0x4C, 0x00, 0x62, 0x00,
    0x76, 0x00, 0x88, 0x00,
    0x98, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd210[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xB9, 0x00, 0xA7, 0x00,
    0xD7, 0x00, 0xFD, 0x01,
    0x37, 0x01, 0x63, 0x01,
    0xA7, 0x01, 0xDE, 0x01,
    0xDF, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd211[] = {
    0x11, 0x00, 0x39, 0xC0,
    0xBA, 0x02, 0x10, 0x02,
    0x4B, 0x02, 0x71, 0x02,
    0xA8, 0x02, 0xCF, 0x02,
    0xFA, 0x03, 0x06, 0x03,
    0x1B, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd212[] = {
    0x0D, 0x00, 0x39, 0xC0,
    0xBB, 0x03, 0x35, 0x03,
    0x4B, 0x03, 0x64, 0x03,
    0x84, 0x03, 0xB3, 0x03,
    0xFF, 0xFF, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd213[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFF, 0x10, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd214[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xFB, 0x01, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd215[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xBA, 0x02, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd216[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x35, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd217[] = {
    0x03, 0x00, 0x39, 0xC0,
    0x51, 0x00, 0x00, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd218[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x53, 0x2C, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd219[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x55, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd220[] = {
    0x03, 0x00, 0x39, 0xC0,
    0x68, 0x02, 0x01, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd221[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x11, 0x00, 0xFF, 0xFF};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd222[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x29, 0x00, 0xFF, 0xFF};




static struct mipi_dsi_cmd bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_command[] = {
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd0, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd1, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd2, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd3, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd4, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd5, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd6, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd7, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd8, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd9, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd10, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd11, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd12, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd13, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd14, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd15, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd16, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd17, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd18, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd19, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd20, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd21, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd22, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd23, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd24, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd25, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd26, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd27, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd28, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd29, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd30, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd31, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd32, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd33, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd34, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd35, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd36, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd37, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd38, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd39, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd40, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd41, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd42, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd43, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd44, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd45, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd46, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd47, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd48, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd49, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd50, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd51, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd52, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd53, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd54, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd55, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd56, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd57, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd58, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd59, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd60, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd61, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd62, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd63, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd64, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd65, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd66, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd67, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd68, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd69, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd70, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd71, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd72, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd73, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd74, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd75, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd76, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd77, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd78, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd79, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd80, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd81, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd82, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd83, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd84, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd85, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd86, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd87, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd88, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd89, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd90, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd91, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd92, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd93, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd94, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd95, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd96, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd97, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd98, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd99, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd100, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd101, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd102, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd103, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd104, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd105, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd106, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd107, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd108, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd109, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd110, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd111, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd112, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd113, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd114, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd115, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd116, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd117, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd118, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd119, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd120, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd121, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd122, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd123, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd124, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd125, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd126, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd127, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd128, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd129, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd130, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd131, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd132, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd133, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd134, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd135, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd136, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd137, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd138, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd139, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd140, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd141, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd142, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd143, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd144, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd145, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd146, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd147, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd148, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd149, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd150, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd151, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd152, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd153, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd154, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd155, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd156, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd157, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd158, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd159, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd160, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd161, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd162, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd163, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd164, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd165, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd166, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd167, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd168, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd169, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd170, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd171, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd172, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd173, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd174, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd175, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd176, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd177, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd178, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd179, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd180, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd181, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd182, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd183, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd184, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd185, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd186, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd187, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd188, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd189, 0x00},
{0x14, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd190, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd191, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd192, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd193, 0x00},
{0x14, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd194, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd195, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd196, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd197, 0x00},
{0x14, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd198, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd199, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd200, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd201, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd202, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd203, 0x00},
{0x14, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd204, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd205, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd206, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd207, 0x00},
{0x14, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd208, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd209, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd210, 0x00},
{0x18, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd211, 0x00},
{0x14, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd212, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd213, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd214, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd215, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd216, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd217, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd218, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd219, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd220, 0x00},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd221, 0x64},
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_on_cmd222, 0x00}
};
#define BKK_AL00AHN_VA_TXD_INX_NT36525_6P26_720P_VIDEO_ON_COMMAND 223


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_off_cmd0[] = {
    0x28, 0x00, 0x05, 0x80};


static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_off_cmd1[] = {
    0x10, 0x00, 0x05, 0x80};




static struct mipi_dsi_cmd bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_off_command[] = {
{0x4, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_off_cmd0, 0x14},
{0x4, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_off_cmd1, 0x96}
};
#define BKK_AL00AHN_VA_TXD_INX_NT36525_6P26_720P_VIDEO_OFF_COMMAND 2


static struct command_state bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_state = {
        0, 0 
};

/*-----------------------------------------------------------------------*/
/* Command mode panel                                                    */
/*-----------------------------------------------------------------------*/
static struct commandpanel_info bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_command_panel = {
        0, 1, 1, 0, 0, 0x2c, 0, 0, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Video mode panel                                                      */
/*-----------------------------------------------------------------------*/
static struct videopanel_info bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_video_panel = {
        1, 0, 0, 0, 1, 1, 2, 0, 0x9 
};

/*-----------------------------------------------------------------------*/
/* Lane configuration                                                    */
/*-----------------------------------------------------------------------*/
static struct lane_configuration bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_lane_config = {
        3, 0, 1, 1, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel timing                                                          */
/*-----------------------------------------------------------------------*/
static const uint32_t bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_timings[]= {
        0x22, 0x1E, 0x07, 0x08, 0x04, 0x03, 0x04, 0xA0,
                        0x22, 0x1E, 0x07, 0x08, 0x04, 0x03, 0x04, 0xA0,
                        0x22, 0x1E, 0x07, 0x08, 0x04, 0x03, 0x04, 0xA0,
                        0x22, 0x1E, 0x07, 0x08, 0x04, 0x03, 0x04, 0xA0,
                        0x22, 0x17, 0x06, 0x07, 0x04, 0x03, 0x04, 0xA0 
};

static struct panel_timing bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_timing_info = {
        0, 4, 0x0C, 0x2A 
};

/*-----------------------------------------------------------------------*/
/* Panel reset sequence                                                  */
/*-----------------------------------------------------------------------*/
static struct panel_reset_sequence bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_reset_seq = {
    { 1, 0, 1, }, { 1, 1, 11, }, 2
};

/*-----------------------------------------------------------------------*/
/* Backlight setting                                                     */
/*-----------------------------------------------------------------------*/
static struct backlight bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_backlight = {
        2, 11, 2047, 1, 2, 0 
};

/*-----------------------------------------------------------------------*/
/* Labibb setting                                                        */
/*-----------------------------------------------------------------------*/
static struct labibb_desc bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_labibb = {
        0, 1, 6000000, 6000000, 6000000, 6000000, 1, 0, 1, 1, 0 
};

/*-----------------------------------------------------------------------*/
/* turn on backlight delay                                               */
/*-----------------------------------------------------------------------*/
int bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_mdp_pipe_type  = MDSS_MDP_PIPE_TYPE_RGB;

int bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_dsi_pll_type  = DSI_PLL_TYPE_THULIUM;

int bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_mipi_signature  = 0xffff;

static const uint32_t bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_regulator_setting[]= {
        0x1d, 0x1d, 0x1d, 0x1d, 0x1d 
};

/*-----------------------------------------------------------------------*/
/* platform Config                                                       */
/*-----------------------------------------------------------------------*/
static struct lcdkit_platform_config bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_panel_platform_config = {
        0, 0, 0, 0, 0x10002, 0x10000, 0x200, 0x20, 64, 0, 0, 61, 0, 
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6000000, 6000000, 100, 20, 0, 
        0, 0, 0, 0, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* misc Information                                                      */
/*-----------------------------------------------------------------------*/
static struct lcdkit_misc_info bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_panel_misc_info = {
        0, 1, 2, 0x01, 0x01, 0x01, 0x01, 0, 1, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* delay ctrl                                                            */
/*-----------------------------------------------------------------------*/
static struct lcdkit_delay_ctrl bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_panel_delay_ctrl = {
        0, 2, 0, 1, 11, 0, 1, 1, 0, 0, 0, 0, 1, 0, 50 
};

static char bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_backlight_cmd0[] = {
    0x03, 0x00, 0x39, 0xC0,
    0x51, 0x00, 0x00, 0xFF};




static struct mipi_dsi_cmd bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_backlight_command[] = {
{0x8, bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_backlight_cmd0, 0x00}
};
#define BKK_AL00AHN_VA_TXD_INX_NT36525_6P26_720P_VIDEO_BACKLIGHT_COMMAND 1



static struct lcd_bias_voltage_info * bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_bias_ic_array[0];
 
#define BKK_AL00AHN_VA_TXD_INX_NT36525_6P26_720P_VIDEO_BIAS_IC_ARRAY 0


static struct backlight_ic_info * bkk_al00ahn_va_txd_inx_nt36525_6p26_720p_video_backlight_ic_array[0];
 
#define BKK_AL00AHN_VA_TXD_INX_NT36525_6P26_720P_VIDEO_BACKLIGHT_IC_ARRAY 0


#endif /*_PANEL_BKK_AL00AHN_VA_TXD_INX_NT36525_6P26_720P_VIDEO_H_*/
